# Generated by Django 6.0.1 on 2026-01-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
