# Generated by Django 6.0.2 on 2026-03-28 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_produce_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_delivery_date', models.DateField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, help_text='Why this counter-offer was made')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('time_slot_start', models.TimeField()),
                ('time_slot_end', models.TimeField()),
                ('delivery_location', models.CharField(blank=True, max_length=300)),
                ('special_instructions', models.TextField(blank=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'time_slot_start'],
            },
        ),
        migrations.CreateModel(
            name='PriceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecasted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('factors', models.JSONField(blank=True, default=dict, help_text='JSON dict of price influencing factors')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forecast_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['produce', '-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('farmer', 'Farmer Rating'), ('restaurant', 'Restaurant Rating')], max_length=20)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year-Round')], max_length=50)),
                ('historical_yield_multiplier', models.FloatField(default=1.0, help_text='1.0 = normal, >1.0 = higher yield')),
                ('price_multiplier', models.FloatField(default=1.0, help_text='Seasonal price adjustment')),
                ('optimal_temperature_min', models.FloatField(blank=True, help_text='Celsius', null=True)),
                ('optimal_temperature_max', models.FloatField(blank=True, null=True)),
                ('optimal_rainfall_mm', models.FloatField(blank=True, help_text='MM per month', null=True)),
                ('current_weather_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('growth_stage', models.CharField(blank=True, help_text='E.g., Germination, Vegetative, Flowering, Harvesting', max_length=100)),
                ('quality_impact', models.FloatField(default=1.0, help_text='1.0 = no impact, >1.0 = positive, <1.0 = negative')),
                ('yield_impact', models.FloatField(default=1.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('forecast_notes', models.TextField(blank=True)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Seasonal Influences',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='minimum_freshness_required',
            field=models.CharField(choices=[('fresh', 'Fresh (Harvested Today)'), ('very_good', 'Very Good (1-2 days old)'), ('good', 'Good (3-5 days old)'), ('fair', 'Fair (6-10 days old)'), ('aged', 'Aged/Processed')], default='very_good', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='negotiation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='negotiation_status',
            field=models.CharField(choices=[('no_offer', 'No Counter Offer'), ('counter_pending', 'Counter Offer Pending'), ('counter_accepted', 'Counter Offer Accepted'), ('counter_rejected', 'Counter Offer Rejected')], default='no_offer', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='original_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_time_start',
            field=models.TimeField(blank=True, help_text='HH:MM format', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quality_requirements',
            field=models.TextField(blank=True, help_text='Specific quality standards'),
        ),
        migrations.AddField(
            model_name='produce',
            name='base_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='current_price_multiplier',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AddField(
            model_name='produce',
            name='demand_forecast_score',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='produce',
            name='estimated_yield_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='freshness_grade',
            field=models.CharField(choices=[('fresh', 'Fresh (Harvested Today)'), ('very_good', 'Very Good (1-2 days old)'), ('good', 'Good (3-5 days old)'), ('fair', 'Fair (6-10 days old)'), ('aged', 'Aged/Processed')], default='fresh', max_length=20),
        ),
        migrations.AddField(
            model_name='produce',
            name='freshness_score',
            field=models.FloatField(default=9.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='produce',
            name='growing_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='produce',
            name='harvested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='is_dynamic_priced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produce',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='optimal_weather_conditions',
            field=models.CharField(blank=True, help_text='Conditions that maximize yield', max_length=500),
        ),
        migrations.AddField(
            model_name='produce',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='E.g., Organic, Pesticide-free, etc.'),
        ),
        migrations.AddField(
            model_name='produce',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year-Round')], default='year_round', max_length=20),
        ),
        migrations.AddField(
            model_name='produce',
            name='shelf_life_days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='produce',
            name='spoilage_risk_percentage',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='produce',
            name='storage_condition',
            field=models.CharField(choices=[('ambient', 'Ambient Temperature'), ('cool', 'Cool Storage'), ('cold', 'Refrigerated'), ('frozen', 'Frozen')], default='ambient', max_length=20),
        ),
        migrations.AddField(
            model_name='produce',
            name='supply_competition',
            field=models.IntegerField(default=0, help_text='Number of competitors selling same item'),
        ),
        migrations.AddField(
            model_name='produce',
            name='weather_dependent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='successful_transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='core_order_restaur_fead6b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['farmer', 'status'], name='core_order_farmer__5e661f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['preferred_delivery_date'], name='core_order_preferr_bf800c_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['farmer', 'status'], name='core_produc_farmer__23aa17_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['expiry_date'], name='core_produc_expiry__05411e_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['freshness_score'], name='core_produc_freshne_98d32f_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['demand_forecast_score'], name='core_produc_demand__5b8f94_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'trust_score'], name='core_user_role_3a83d8_idx'),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='core.order'),
        ),
        migrations.AddField(
            model_name='deliverywindow',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_window', to='core.order'),
        ),
        migrations.AddField(
            model_name='priceforecast',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_forecasts', to='core.produce'),
        ),
        migrations.AddField(
            model_name='rating',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.order'),
        ),
        migrations.AddField(
            model_name='rating',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seasonalinfluence',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_influences', to='core.produce'),
        ),
        migrations.AddIndex(
            model_name='counteroffer',
            index=models.Index(fields=['order', 'status'], name='core_counte_order_i_fcfec7_idx'),
        ),
        migrations.AddIndex(
            model_name='counteroffer',
            index=models.Index(fields=['created_by', 'status'], name='core_counte_created_49c3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='priceforecast',
            index=models.Index(fields=['produce', 'forecast_date'], name='core_pricef_produce_838ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='priceforecast',
            index=models.Index(fields=['forecast_date'], name='core_pricef_forecas_c19607_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='priceforecast',
            unique_together={('produce', 'forecast_date')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['to_user', 'score'], name='core_rating_to_user_4e0126_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating_type', 'score'], name='core_rating_rating__2dbe3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('from_user', 'to_user', 'order')},
        ),
        migrations.AddIndex(
            model_name='seasonalinfluence',
            index=models.Index(fields=['produce', 'season'], name='core_season_produce_12b156_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalinfluence',
            index=models.Index(fields=['recorded_date'], name='core_season_recorde_ff1f77_idx'),
        ),
    ]
