# Generated by Django 6.0.2 on 2026-03-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_counteroffer_deliverywindow_priceforecast_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='freshness_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='produce_state',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('aging', 'Aging'), ('near_expiry', 'Near Expiry'), ('expired', 'Expired'), ('unavailable', 'Unavailable')], default='fresh', max_length=20),
        ),
    ]
