# Generated by Django 4.2.29 on 2026-04-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produce_freshness_last_updated_produce_produce_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
