# Generated by Django 4.2.29 on 2026-04-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produce_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('pulses', 'Pulses'), ('dairy', 'Dairy'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
